---
title: "Assignment 1"
author: "Weijie Gao"
date: "10/10/2017"
output:
  pdf_document: default
---

```{r}
dataPath <- "/Users/gaoweijie/Google Drive/2017 Fall/Machine Learning/Assignment1"
college <- read.csv(paste(dataPath,"College.csv",sep='/'),header=TRUE)
dim(college)
```

```{r}
college <- college[,-1]
# fix(college)
```

```{r}
summary(college)
```

```{r}
pairs(college[,1:10])
```
```{r}
# private <- as.factor(college$Private)
plot(college$Private,college$Outstate)
```
```{r}
Elite <- rep ("No",nrow(college ))
Elite[college$Top10perc >50]="Yes"
Elite <- as.factor (Elite)
college <- data.frame(college ,Elite)

summary(college$Elite)

plot(college$Elite,college$Outstate)
```
```{r}
par(mfrow=c(2,2))
hist(college$PhD,col='lightblue',main="Histogram of PhD", xlab= 'PhD')
hist(college$Accept,col='lightblue',main="Histogram of Accept", xlab= 'Accept')
hist(college$Enroll,col='lightblue',main="Histogram of Enroll", xlab= 'Enroll')
hist(college$S.F.Ratio,col='lightblue',main="Histogram of S.F.Ratio", xlab= 'S.F.Ratio')
```
```{r}
elite_grad <- college$Grad.Rate[college$Elite == "Yes"]
nonelit_grad <- college$Grad.Rate[college$Elite == "No"]
summary(elite_grad)
summary(nonelit_grad)
plot(college$Elite,college$Grad.Rate,main='Graduation Rate',col='pink')
```

### Based on the above analysis, the mean graduation rate for elite student is 63.46 while the mean graduation rate for non elite student is 83.38, which shows that elite student prone to have a higher graduatjion rate.

